version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
       - "./.db_import:/docker-entrypoint-initdb.d"
     restart: always
     env_file:
       - "./.db-secret"

   nginx:
     depends_on:
       - drupal
       - s3-proxy
     image: nginx:stable
     volumes:
       - "./nginx.conf.d:/etc/nginx/conf.d"
       - "./.data/files/kuradiauk:/usr/share/nginx/kuradiauk"
     ports:
       - "80:80"
     links:
       - drupal
       - s3-proxy
     restart: always

   s3-proxy:
     image: coopernurse/nginx-s3-proxy
     volumes:
       - "./s3-proxy.conf:/nginx.conf"
       - "./s3-proxy-common.conf:/s3-proxy-common.conf"
       - "./.s3-proxy-secret.conf:/s3-secret.conf"
     restart: always

   drupal:
     depends_on:
       - db
     image: drupal:7.51-apache
     volumes:
       - "./.data/cms/myx:/var/www/html"
     links:
       - db
     restart: always

   modx:
     depends_on:
       - db
     image: gerasim13/modx-docker
     volumes:
       - "./.data/cms/aqtest:/var/www/html"
     links:
       - db:mysql
     restart: always
