version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
       - "./.db_import:/docker-entrypoint-initdb.d"
     restart: always
     env_file:
       - "./.db-secret"

   certbot:
     image: salemove/letsencrypt-dns
     volumes:
       - "le-certs:/certs"
     restart: always
     environment:
       - PROVIDER=route53
       - CERTBOT_DOMAIN=*.ostankin.net
       - CERTBOT_ALIAS=myx.ostankin.net
     env_file:
       - "./.certbot-secret"

   nginx:
     depends_on:
       - drupal
       - certbot
     image: nginx:stable
     volumes:
       - "le-certs:/certs"
       - "./nginx.conf.d:/etc/nginx/conf.d"
       - "./.data/files/kuradiauk:/usr/share/nginx/kuradiauk"
       - "./.data/files/pshortcut:/usr/share/nginx/pshortcut"
       - "./.data/files/root:/usr/share/nginx/root"
       - "./.data/files/aboutbears:/usr/share/nginx/aboutbears"
     ports:
       - "80:80"
       - "443:443"
     links:
       - drupal
     restart: always

   drupal:
     depends_on:
       - db
     image: drupal:7.51-apache
     volumes:
       - "./.data/cms/myx:/var/www/html"
     links:
       - db
     restart: always

volumes:
  le-certs:
