version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - "./.data/db:/var/lib/mysql"
       - "./.db_import:/docker-entrypoint-initdb.d"
     restart: always
     env_file:
       - "./.env/db"
       - "./.env/db-secret"

   drupal:
     depends_on:
       - db
     image: drupal:7.51-apache
     volumes:
       - "./.data/cms:/var/www/html"
     links:
       - db
     ports:
       - "80:80"
     restart: always
